---
apiVersion: v1
kind: Namespace
metadata:
  name: app-teste
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: app-teste
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: app-teste
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
  namespace: app-teste 
  labels:
    app: mysql 
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql 
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pvc 
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1 
kind: Service 
metadata:
  name: wordpress
  namespace: app-teste 
  labels:
    app: wordpress 
spec:
  ports: 
    - port: 80
  selector: 
    app: wordpress 
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: app-teste
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: wordpress 
  namespace: app-teste
  labels:
    app: wordpress 
spec:
  selector:
    matchLabels:
      app: wordpress 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress 
          image: wordpress:4.8-apache
          env: 
            - name: WORDPRESS_DB_HOST
              value: mysql.app-teste.svc.cluster.local
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports: 
            - name: http
              containerPort: 80
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 40
          #   periodSeconds: 5
          #   failureThreshold: 1
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 40
          #   periodSeconds: 5
          #   failureThreshold: 1
          volumeMounts:
            - name: wordpress-pvc
              mountPath: /var/www/html
      volumes:
        - name: wordpress-pvc 
          persistentVolumeClaim:
            claimName: wordpress-pvc